version: 1
disable_existing_loggers: False

formatters:
  console:
    format: "[%(levelname)s] %(message)s"

  file:
    format: "%(asctime)s | %(levelname)s | %(name)s | %(filename)s:%(lineno)d | %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: console
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: file
    filename: app.log
    maxBytes: 2000000
    backupCount: 5
    encoding: utf-8

loggers:
  myapp:
    level: INFO
    handlers: [console, file]
    propagate: False

root:
  level: INFO
  handlers: [console]
